/* ============================================================
   DealHub Vietnam — Mock Data
   Deals, categories, livestreams, video reviews, businesses
   ============================================================ */

export const DH_DATA = {
    cities: ["Hồ Chí Minh", "Hà Nội", "Đà Nẵng", "Nha Trang", "Phú Quốc", "Đà Lạt"],

    categories: [
        { id: "spa", name: "Spa & Làm đẹp", emoji: "💆‍♀️", count: 0 },
        { id: "restaurant", name: "Nhà hàng", emoji: "🍽️", count: 0 },
        { id: "travel", name: "Du lịch", emoji: "🏝️", count: 0 },
        { id: "golf", name: "Golf", emoji: "⛳", count: 0 },
        { id: "health", name: "Khám sức khỏe", emoji: "💉", count: 0 },
        { id: "event", name: "Vé sự kiện", emoji: "🎫", count: 0 },
        { id: "hotel", name: "Khách sạn", emoji: "🏨", count: 0 },
        { id: "beauty", name: "Thẩm mỹ", emoji: "💅", count: 0 },
    ],

    deals: [
        {
            id: "d1",
            title: "Spa VIP 90 phút - Massage Thái cổ điển + gội đầu dưỡng sinh",
            biz: "Annam Spa Premium",
            category: "spa",
            emoji: "💆‍♀️",
            oldPrice: 1000000,
            newPrice: 399000,
            rating: 4.8,
            reviews: 1240,
            distance: 1.2,
            city: "Hồ Chí Minh",
            sold: 3200,
            left: 18,
            featured: true,
            highlights: [
                "Massage Thái 60 phút bởi kỹ thuật viên 5 năm kinh nghiệm",
                "Gội đầu dưỡng sinh 30 phút với thảo dược thiên nhiên",
                "Phòng riêng, trà thảo mộc, khăn ướt nóng",
                "Áp dụng cả cuối tuần không phụ phí",
            ],
            desc: "Biến giờ vắng khách ngày thường thành doanh thu. An Nam Spa mở deal độc quyền giúp bạn trải nghiệm dịch vụ 5 sao với giá 3 sao.",
        },
        {
            id: "d2",
            title: "Buffet Nhật 80 món - Tối thứ 2 đến thứ 5",
            biz: "Kichi Kichi Sushi House",
            category: "restaurant",
            emoji: "🍣",
            oldPrice: 850000,
            newPrice: 459000,
            rating: 4.7,
            reviews: 890,
            distance: 3.5,
            city: "Hồ Chí Minh",
            sold: 1800,
            left: 25,
            featured: true,
            highlights: [
                "80 món Nhật: sashimi, sushi, tempura, teppanyaki",
                "Bàn trống tối thứ 2-5 được lấp đầy với giá ưu đãi",
                "Bao gồm đồ uống: trà xanh, sake nhẹ",
                "Trẻ em dưới 6 tuổi miễn phí",
            ],
            desc: "Nhà hàng lấp đầy công suất nhàn rỗi bằng cách giảm giá sâu các buổi tối ngày thường.",
        },
        {
            id: "d3",
            title: "Resort 5 sao Phú Quốc 2N1Đ - Full board + đưa đón sân bay",
            biz: "Peach Bay Resort & Spa",
            category: "travel",
            emoji: "🏝️",
            oldPrice: 4500000,
            newPrice: 1990000,
            rating: 4.9,
            reviews: 560,
            distance: 0,
            city: "Phú Quốc",
            sold: 740,
            left: 8,
            featured: true,
            highlights: [
                "Villa hướng vườn 2 đêm 1 ngày, full board 3 bữa",
                "Đưa đón sân bay 2 chiều",
                "Miễn phí kayak, snorkeling, xe đạp",
                "Mùa thấp điểm - giá tốt nhất năm",
            ],
            desc: "Resort biến công suất nhàn rỗi mùa thấp điểm thành doanh thu, người dùng được nghỉ dưỡng 5 sao giá 2 sao.",
        },
        {
            id: "d4",
            title: "Golf 18 hole cuối tuần - Green fee + caddie + xe điện",
            biz: "Twin Doves Golf Club",
            category: "golf",
            emoji: "⛳",
            oldPrice: 2800000,
            newPrice: 1490000,
            rating: 4.6,
            reviews: 320,
            distance: 12.0,
            city: "Hồ Chí Minh",
            sold: 410,
            left: 12,
            featured: true,
            highlights: [
                "18 hole championship course",
                "Bao gồm green fee, caddie, xe điện, locker",
                "Áp dụng sáng thứ 7 & CN",
                "Tặng 1 phần breakfast set",
            ],
            desc: "Sân golf lấp đầy tee-time trống cuối tuần sáng sớm.",
        },
        {
            id: "d5",
            title: "Gói khám sức khỏe tổng quát tiêu chuẩn - 50 chỉ số",
            biz: "Tâm Anh Medical Center",
            category: "health",
            emoji: "💉",
            oldPrice: 3500000,
            newPrice: 1890000,
            rating: 4.8,
            reviews: 1500,
            distance: 5.4,
            city: "Hồ Chí Minh",
            sold: 2600,
            left: 30,
            featured: false,
            highlights: [
                "Khám tổng quát 50 chỉ số: máu, nước tiểu, X-quang, siêu âm",
                "Tư vấn bác sĩ chuyên khoa 1-1",
                "Kết quả trong 24h qua app",
                "Nhận kết quả tận nhà miễn phí",
            ],
            desc: "Lấp đầy khung giờ khám buổi chiều - khi phòng khám ít khách.",
        },
        {
            id: "d6",
            title: "Concert Đen Vâu - Live at Saigon Arena",
            biz: "Saigon Arena",
            category: "event",
            emoji: "🎫",
            oldPrice: 1500000,
            newPrice: 890000,
            rating: 4.9,
            reviews: 2300,
            distance: 8.1,
            city: "Hồ Chí Minh",
            sold: 5400,
            left: 5,
            featured: true,
            highlights: [
                "Vé khu vực Standing Gold",
                "Mở cửa 18:00, bắt đầu 19:30",
                "Quà tặng: poster + sticker pack",
                "Giới hạn 5 vé cuối cùng",
            ],
            desc: "Sự kiện bán lấp đầy ghế trống trước show 3 ngày.",
        },
        {
            id: "d7",
            title: "Khách sạn 4 sao trung tâm Đà Nẵng - 1 đêm + buffet sáng",
            biz: "Hương Bình Hotel",
            category: "hotel",
            emoji: "🏨",
            oldPrice: 1800000,
            newPrice: 720000,
            rating: 4.5,
            reviews: 680,
            distance: 0,
            city: "Đà Nẵng",
            sold: 920,
            left: 15,
            featured: false,
            highlights: [
                "Phòng Deluxe 32m2, view thành phố",
                "Buffet sáng 2 người",
                "Hồ bơi, gym, spa giảm 20%",
                "Cách biển 5 phút đi bộ",
            ],
            desc: "Khách sạn lấp phòng trống ngày thường.",
        },
        {
            id: "d8",
            title: "Làm nail + design gel - Manicure + Pedicure full set",
            biz: "Lily Nail Studio",
            category: "beauty",
            emoji: "💅",
            oldPrice: 600000,
            newPrice: 249000,
            rating: 4.7,
            reviews: 410,
            distance: 2.1,
            city: "Hồ Chí Minh",
            sold: 1500,
            left: 20,
            featured: false,
            highlights: [
                "Manicure gel + Pedicure gel",
                "Design 2 móng miễn phí",
                "Sơn OPI chính hãng",
                "Bảo hành 7 ngày",
            ],
            desc: "Studio nail lấp giờ vắng buổi sáng.",
        },
        {
            id: "d9",
            title: "Ăn tối view sông Sài Gòn - Set 5 món cho 2 người",
            biz: "Saigon River Bistro",
            category: "restaurant",
            emoji: "🍷",
            oldPrice: 1200000,
            newPrice: 599000,
            rating: 4.6,
            reviews: 520,
            distance: 4.2,
            city: "Hồ Chí Minh",
            sold: 680,
            left: 10,
            featured: false,
            highlights: [
                "Set 5 món Âu: soup, salad, main, dessert, drink",
                "Bàn ngoài trời view sông",
                "Tặng 1 ly wine pairing",
                "Nhạc acoustic live tối thứ 5-7",
            ],
            desc: "Nhà hàng lấp bàn trống view sông buổi tối sớm.",
        },
        {
            id: "d10",
            title: "Massage body đá nóng 60 phút - Giải độc cơ thể",
            biz: "Thiên Đường Spa",
            category: "spa",
            emoji: "💆",
            oldPrice: 700000,
            newPrice: 299000,
            rating: 4.5,
            reviews: 890,
            distance: 1.8,
            city: "Hà Nội",
            sold: 2100,
            left: 22,
            featured: false,
            highlights: [
                "Massage đá nóng 60 phút",
                "Tẩy tế bào chết toàn thân",
                "Ủ dưỡng ẩm tinh dầu lavender",
                "Trà gừng mật ong",
            ],
            desc: "Spa Hà Nội lấp giờ vắng buổi chiều.",
        },
        {
            id: "d11",
            title: "Tour Đà Lạt 2N1Đ - Trekking + Thác + Vườn dâu",
            biz: "Dalat Adventure Tours",
            category: "travel",
            emoji: "🏔️",
            oldPrice: 2500000,
            newPrice: 1190000,
            rating: 4.8,
            reviews: 340,
            distance: 0,
            city: "Đà Lạt",
            sold: 480,
            left: 9,
            featured: false,
            highlights: [
                "Trekking Langbiang + thác Datanla",
                "Hái dâu, vườn hoa hồng, làng hoa",
                "Homestay 2 sao chuẩn, 3 bữa",
                "HDV tiếng Việt + Anh",
            ],
            desc: "Tour lấp chỗ trống cuối tuần.",
        },
        {
            id: "d12",
            title: "Tiêm filler môi - Bác sĩ chuyên khoa da liễu",
            biz: "Seoul Aesthetic Clinic",
            category: "beauty",
            emoji: "💉",
            oldPrice: 9000000,
            newPrice: 4500000,
            rating: 4.9,
            reviews: 280,
            distance: 6.3,
            city: "Hồ Chí Minh",
            sold: 190,
            left: 6,
            featured: false,
            highlights: [
                "Filler Juvederm Ultra chính hãng",
                "Bác sĩ chuyên khoa da liễu 10 năm KN",
                "Tái khám miễn phí 2 lần",
                "Bảo hành 1 năm",
            ],
            desc: "Thẩm mỹ viện lấp khung giờ vắng.",
        },
    ],

    livestreams: [
        {
            id: "l1",
            title: "Flash sale 50% - Tất cả deal spa hôm nay!",
            biz: "Annam Spa Premium",
            emoji: "💆‍♀️",
            viewers: 1240,
            dealTitle: "Spa VIP 90 phút",
            dealPrice: 399000,
        },
        {
            id: "l2",
            title: "Ăn thử buffet Nhật 80 món - Review thật",
            biz: "Kichi Kichi Sushi House",
            emoji: "🍣",
            viewers: 890,
            dealTitle: "Buffet Nhật 80 món",
            dealPrice: 459000,
        },
        {
            id: "l3",
            title: "Tour Phú Quốc - Q&A trực tiếp từ resort",
            biz: "Peach Bay Resort & Spa",
            emoji: "🏝️",
            viewers: 560,
            dealTitle: "Resort 2N1Đ Phú Quốc",
            dealPrice: 1990000,
        },
        {
            id: "l4",
            title: "Golf challenge - Ai đánh hole-in-one tặng deal",
            biz: "Twin Doves Golf Club",
            emoji: "⛳",
            viewers: 320,
            dealTitle: "Golf 18 hole",
            dealPrice: 1490000,
        },
        {
            id: "l5",
            title: "Livestream bán vé concert Đen Vâu",
            biz: "Saigon Arena",
            emoji: "🎤",
            viewers: 3200,
            dealTitle: "Vé concert",
            dealPrice: 890000,
        },
        {
            id: "l6",
            title: "Khám sức khỏe miễn phí - Tư vấn bác sĩ live",
            biz: "Tâm Anh Medical Center",
            emoji: "💉",
            viewers: 410,
            dealTitle: "Gói khám tổng quát",
            dealPrice: 1890000,
        },
    ],

    videos: [
        {
            id: "v1",
            title: "Review Spa VIP 90 phút - Có đáng tiền không?",
            author: "Foodie Trang",
            avatar: "👩",
            emoji: "💆‍♀️",
            duration: "2:45",
            views: "120K",
        },
        {
            id: "v2",
            title: "Ăn hết 80 món buffet Nhật - Challenge",
            author: "An Ngôn",
            avatar: "👨",
            emoji: "🍣",
            duration: "3:12",
            views: "340K",
        },
        {
            id: "v3",
            title: "Phú Quốc 2N1Đ - Resort 5 sao giá 2 sao",
            author: "Travel Bee",
            avatar: "🧑",
            emoji: "🏝️",
            duration: "4:30",
            views: "560K",
        },
        {
            id: "v4",
            title: "Đánh golf ở Twin Doves - Course review",
            author: "Golf Master",
            avatar: "🏌️",
            emoji: "⛳",
            duration: "5:20",
            views: "89K",
        },
        {
            id: "v5",
            title: "Concert Đen Vâu - HIGHLIGHTS",
            author: "Music Live",
            avatar: "🎤",
            emoji: "🎵",
            duration: "1:58",
            views: "1.2M",
        },
        {
            id: "v6",
            title: "Khám sức khỏe tổng quát - Trải nghiệm thật",
            author: "Doctor Minh",
            avatar: "👨‍⚕️",
            emoji: "💉",
            duration: "3:40",
            views: "210K",
        },
    ],
};
